version: '3.8'

services:
  web:
    build:
      context: ./django
    container_name: django_server
    command: sh -c "python3 wait_for_db.py && python3 ./mysite/manage.py runserver 0.0.0.0:8000"
    expose:
      - 8000
    volumes:
      - ./django/:/code/
    env_file:
      - "./django/.env"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx_REVproxy
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - web

  db:
    image: mysql
    container_name: mysql_db
    volumes:
      - ./MySQL/data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      - MYSQL_ROOT_PASSWORD=harasisco
      - MYSQL_DATABASE=my_database
