version: '3.8'

services:
  web:
    build:
      context: ./django
    container_name: django_server
    hostname: Django_server
    command: sh -c "python3 wait_for_db.py && python3 ./mysite/manage.py runserver 0.0.0.0:8000"
    expose:
      - 8000
    volumes:
      - ./django/:/code/
    env_file:
      - "./django/.env"
    depends_on:
      - db
    networks:
      test:
        ipv4_address: 10.0.0.10
        
        
  nginx:
    image: nginx:latest
    container_name: nginx_REVproxy
    hostname: nginx_REVproxy
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - web
    networks:
      test:
        ipv4_address: 10.0.0.5
  
  
  db:
    image: mysql
    container_name: mysql_db
    hostname: MySQL
    volumes:
      - ./MySQL/data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      - MYSQL_ROOT_PASSWORD=harasisco
      - MYSQL_DATABASE=my_database
    networks:
      test:
        ipv4_address: 10.0.0.15
        
        
        
networks:
  test:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
